primary:
  persistence:
    enabled: true
    existingClaim: mariadb-pvc

auth:
  rootPassword: "thdms1431"
  database: edu

initdbScripts:
  init.sql: |
    CREATE TABLE test (
      id INT AUTO_INCREMENT PRIMARY KEY,
      name VARCHAR(50)
    );
    INSERT INTO test (name) VALUES ('hello');
